_verbs = '''
    accept
    care
    could
    enjoy
    happen
    lead
    open
    reduce
    settle
    teach
    account
    carry
    count
    examine
    hate
    learn
    order
    refer
    shake
    tell
    achieve
    catch
    cover
    exist
    have
    leave
    ought
    reflect
    shall
    tend
    act
    cause
    create
    expect
    head
    lend
    own
    refuse
    share
    test
    add
    change
    cross
    experience
    hear
    let
    pass
    regard
    shoot
    thank
    admit
    charge
    cry
    explain
    help
    lie
    pay
    relate
    should
    think
    affect
    check
    cut
    express
    hide
    like
    perform
    release
    shout
    throw
    afford
    choose
    damage
    extend
    hit
    limit
    pick
    remain
    show
    touch
    agree
    claim
    dance
    face
    hold
    link
    place
    remember
    shut
    train
    aim
    clean
    deal
    fail
    hope
    listen
    plan
    remove
    sing
    travel
    allow
    clear
    decide
    fall
    hurt
    live
    play
    repeat
    sit
    treat
    answer
    climb
    deliver
    fasten
    identify
    look
    point
    replace
    sleep
    try
    appear
    close
    demand
    feed
    imagine
    lose
    prefer
    reply
    smile
    turn
    apply
    collect
    deny
    feel
    improve
    love
    prepare
    report
    sort
    understand
    argue
    come
    depend
    fight
    include
    make
    present
    represent
    sound
    use
    arrange
    commit
    describe
    fill
    increase
    manage
    press
    require
    speak
    used to
    arrive
    compare
    design
    find
    indicate
    mark
    prevent
    rest
    stand
    visit
    ask
    complain
    destroy
    finish
    influence
    matter
    produce
    result
    start
    vote
    attack
    complete
    develop
    fit
    inform
    may
    promise
    return
    state
    wait
    avoid
    concern
    die
    fly
    intend
    mean
    protect
    reveal
    stay
    walk
    base
    confirm
    disappear
    fold
    introduce
    measure
    prove
    ring
    stick
    want
    be
    connect
    discover
    follow
    invite
    meet
    provide
    rise
    stop
    warn
    beat
    consider
    discuss
    force
    involve
    mention
    publish
    roll
    study
    wash
    become
    consist
    divide
    forget
    join
    might
    pull
    run
    succeed
    watch
    begin
    contact
    do
    forgive
    jump
    mind
    push
    save
    suffer
    wear
    believe
    contain
    draw
    form
    keep
    miss
    put
    say
    suggest
    will
    belong
    continue
    dress
    found
    kick
    move
    raise
    see
    suit
    win
    break
    contribute
    drink
    gain
    kill
    must
    reach
    seem
    supply
    wish
    build
    control
    drive
    get
    knock
    need
    read
    sell
    support
    wonder
    burn
    cook
    drop
    give
    know
    notice
    realize
    send
    suppose
    work
    buy
    copy
    eat
    go
    last
    obtain
    receive
    separate
    survive
    worry
    call
    correct
    enable
    grow
    laugh
    occur
    recognize
    serve
    take
    would
    can
    cost
    encourage
    handle
    lay
    offer
    record
    set
    talk
    write
'''

if False:
    _verb_list = ' '.join(_verbs.split('\n')).split()
    _verb_list = [w.strip() for w in _verb_list if w.strip()]
    _verb_list = [w.lower() for w in _verb_list]
    _verb_list = set(_verb_list)

    print '-' * 80
    print '_VERB_LIST = set('
    print '\t\t' + str(sorted(_verb_list, key = lambda x: (x.lower(), x)))
    print '\t)'
else:

    _VERB_LIST = set(
		['accept', 'account', 'achieve', 'act', 'add', 'admit', 'affect', 'afford', 'agree', 'aim', 'allow', 'answer', 'appear', 'apply', 'argue', 'arrange', 'arrive', 'ask', 'attack', 'avoid', 'base', 'be', 'beat', 'become', 'begin', 'believe', 'belong', 'break', 'build', 'burn', 'buy', 'call', 'can', 'care', 'carry', 'catch', 'cause', 'change', 'charge', 'check', 'choose', 'claim', 'clean', 'clear', 'climb', 'close', 'collect', 'come', 'commit', 'compare', 'complain', 'complete', 'concern', 'confirm', 'connect', 'consider', 'consist', 'contact', 'contain', 'continue', 'contribute', 'control', 'cook', 'copy', 'correct', 'cost', 'could', 'count', 'cover', 'create', 'cross', 'cry', 'cut', 'damage', 'dance', 'deal', 'decide', 'deliver', 'demand', 'deny', 'depend', 'describe', 'design', 'destroy', 'develop', 'die', 'disappear', 'discover', 'discuss', 'divide', 'do', 'draw', 'dress', 'drink', 'drive', 'drop', 'eat', 'enable', 'encourage', 'enjoy', 'examine', 'exist', 'expect', 'experience', 'explain', 'express', 'extend', 'face', 'fail', 'fall', 'fasten', 'feed', 'feel', 'fight', 'fill', 'find', 'finish', 'fit', 'fly', 'fold', 'follow', 'force', 'forget', 'forgive', 'form', 'found', 'gain', 'get', 'give', 'go', 'grow', 'handle', 'happen', 'hate', 'have', 'head', 'hear', 'help', 'hide', 'hit', 'hold', 'hope', 'hurt', 'identify', 'imagine', 'improve', 'include', 'increase', 'indicate', 'influence', 'inform', 'intend', 'introduce', 'invite', 'involve', 'join', 'jump', 'keep', 'kick', 'kill', 'knock', 'know', 'last', 'laugh', 'lay', 'lead', 'learn', 'leave', 'lend', 'let', 'lie', 'like', 'limit', 'link', 'listen', 'live', 'look', 'lose', 'love', 'make', 'manage', 'mark', 'matter', 'may', 'mean', 'measure', 'meet', 'mention', 'might', 'mind', 'miss', 'move', 'must', 'need', 'notice', 'obtain', 'occur', 'offer', 'open', 'order', 'ought', 'own', 'pass', 'pay', 'perform', 'pick', 'place', 'plan', 'play', 'point', 'prefer', 'prepare', 'present', 'press', 'prevent', 'produce', 'promise', 'protect', 'prove', 'provide', 'publish', 'pull', 'push', 'put', 'raise', 'reach', 'read', 'realize', 'receive', 'recognize', 'record', 'reduce', 'refer', 'reflect', 'refuse', 'regard', 'relate', 'release', 'remain', 'remember', 'remove', 'repeat', 'replace', 'reply', 'report', 'represent', 'require', 'rest', 'result', 'return', 'reveal', 'ring', 'rise', 'roll', 'run', 'save', 'say', 'see', 'seem', 'sell', 'send', 'separate', 'serve', 'set', 'settle', 'shake', 'shall', 'share', 'shoot', 'should', 'shout', 'show', 'shut', 'sing', 'sit', 'sleep', 'smile', 'sort', 'sound', 'speak', 'stand', 'start', 'state', 'stay', 'stick', 'stop', 'study', 'succeed', 'suffer', 'suggest', 'suit', 'supply', 'support', 'suppose', 'survive', 'take', 'talk', 'teach', 'tell', 'tend', 'test', 'thank', 'think', 'throw', 'to', 'touch', 'train', 'travel', 'treat', 'try', 'turn', 'understand', 'use', 'used', 'visit', 'vote', 'wait', 'walk', 'want', 'warn', 'wash', 'watch', 'wear', 'will', 'win', 'wish', 'wonder', 'work', 'worry', 'would', 'write']
	)

print _VERB_LIST